backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: static/uploads # Media files will be stored in the repo under static/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /uploads
locale: 'en'
site_url: https://dev.bestdictator.com
display_url: https://dev.bestdictator.com
logo_url: /DiC-Icon.png
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "dics" # Used in routes, e.g., /admin/collections/blog
    label: "Dictators" # Used in the UI
    label_singular: "Dictator"
    folder: "static/_dics" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Short name", name: "title", widget: "string"}
      - {label: "Prefix", name: "prefix", widget: "select", options: ["Mr.", "Ms.", "Mrs.", "Dr.", "Sr.", "Jr."], required: false}
      - {label: "First name", name: "firstname", widget: "string", required: false}
      - {label: "Middle name", name: "middlename", widget: "string", required: false}
      - {label: "Last name", name: "lastname", widget: "string"}
      - {label: "Short description", name: "desc", widget: "string"}
      - {label: "Birth date", name: "birthdate", widget: "date", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", required: false}
      - {label: "Death date", name: "deathdate", widget: "date", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", required: false}
      - {label: "Is dead", name: "isdead", widget: "boolean", required: false}
      - {label: "Country", name: "country", widget: "string", required: false}

      - name: "profile"
        label: "Profile"
        widget: "object"
        collapsed: true
        fields: 
          - {label: "Corruption", name: "corruption", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Power hunger", name: "power_hunger", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Agression", name: "agression", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Autocracy", name: "autocracy", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Telling lies", name: "telling_lies", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Manipulation", name: "manipulation", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Narcissism", name: "narcissism", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Megalomania", name: "megalomania", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Psychosis", name: "psychosis", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Militancy", name: "militancy", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Cynicism", name: "cynicism", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Bullshit factor", name: "bullshit1", widget: "number", valueType: "int", min: 1, max: 5, default: 1}

      - name: "power"
        label: "Power indicators"
        widget: "object"
        collapsed: true
        fields: 
          - {label: "Parliament", name: "parliament", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Print Media", name: "print", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Online Media", name: "online", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Television", name: "tv", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Justice Depts", name: "justice", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Economy", name: "economy", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Education", name: "education", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Culture", name: "culture", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Religions", name: "religion", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "State control", name: "state", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Constitution", name: "constitution", widget: "number", valueType: "int", min: 1, max: 5, default: 1}
          - {label: "Bullshit factor", name: "bullshit2", widget: "number", valueType: "int", min: 1, max: 5, default: 1}

      - {label: "Photo", name: "photo", widget: "file", default: "/DiC-Logo.svg", media_library: {config: {multiple: false}}}
      - {label: "Bio", name: "bio", widget: "markdown", minimal: true, required: false}
      - {label: "Description", name: "body", widget: "markdown"}

  - name: "wtfs" # Used in routes, e.g., /admin/collections/blog
    label: "WTFs" # Used in the UI
    label_singular: "WTF"
    folder: "static/_wtfs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "psyche" # Used in routes, e.g., /admin/collections/blog
    label: "Psyche Articles" # Used in the UI
    label_singular: "Psyche Article"
    folder: "static/_psyche" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "living_dics" # Used in routes, e.g., /admin/collections/blog
    label: "Living Dictators" # Used in the UI
    folder: "static/_dics" # The path to the folder where the documents are stored
    filter:
      field: deathdate
      value: ''
    fields:
      - {label: "Name", name: title}
      - {label: "Lost/hiding", name: "lost", widget: "boolean", default: false}

  - name: "dead_dics" # Used in routes, e.g., /admin/collections/blog
    label: "Mausoleum" # Used in the UI
    folder: "static/_dics" # The path to the folder where the documents are stored
    filter:
      field: isdead
      value: true
    fields:
      - {label: "Name", name: title}
      - {label: "Cause of death", name: "cause", widget: "markdown", minimal: true, required: false}

  - name: "tests" # Used in routes, e.g., /admin/collections/blog
    label: "Tests" # Used in the UI
    label_singular: "Test"
    folder: "static/_tests" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Content", name: "body", widget: "markdown"}
      - name: "questions"
        label: "Questions"
        widget: "list"
        collapsed: false
        fields: 
          - {label: "Question", name: "q", widget: "string"}
          - label: Answers
            name: answers
            widget: list
            collapsed: false
            fields:
              - {label: Answer, name: a, widget: string}
              - {label: Value, name: value, widget: number}