backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: static/uploads # Media files will be stored in the repo under static/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /uploads
locale: 'en'
site_url: https://bestdictator.netlify.app
display_url: https://bestdictator.netlify.app
logo_url: /DiC-Logo-B.svg
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "dictators" # Used in routes, e.g., /admin/collections/blog
    label: "Dictator" # Used in the UI
    folder: "static/_dics" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Short name", name: "title", widget: "string"}
      - {label: "Prefix", name: "prefix", widget: "select", options: ["Mr.", "Ms.", "Mrs.", "Dr.", "Sr.", "Jr."], required: false}
      - {label: "First name", name: "firstname", widget: "string", required: false}
      - {label: "Middle name", name: "middlename", widget: "string", required: false}
      - {label: "Last name", name: "lastname", widget: "string"}
      - {label: "Birth date", name: "birthdate", widget: "string", format: "YYYY-MM-DD", required: false, timeFormat: false}
      - {label: "Death date", name: "deathdate", widget: "datetime", format: "YYYY-MM-DD", required: false, timeFormat: false, default: false}
      - {label: "Country", name: "country", widget: "string", required: false}

      - name: "profile"
        label: "Profile"
        widget: "object"
        collapsed: true
        fields: 
          - {label: "Corruption", name: "corruption", widget: "number", valueType: "int", min: 1, max: 5, required: false}
          - {label: "Power hunger", name: "power_hunger", widget: "number", valueType: "int", min: 1, max: 5, required: false}
          - {label: "Agression", name: "agression", widget: "number", valueType: "int", min: 1, max: 5, required: false}
          - {label: "Autocracy", name: "autocracy", widget: "number", valueType: "int", min: 1, max: 5, required: false}
          - {label: "Telling lies", name: "telling_lies", widget: "number", valueType: "int", min: 1, max: 5, required: false}
          - {label: "Manipulation", name: "manipulation", widget: "number", valueType: "int", min: 1, max: 5, required: false}
          - {label: "Narcissism", name: "narcissism", widget: "number", valueType: "int", min: 1, max: 5, required: false}
          - {label: "Megalomania", name: "megalomania", widget: "number", valueType: "int", min: 1, max: 5, required: false}
          - {label: "Psychosis", name: "psychosis", widget: "number", valueType: "int", min: 1, max: 5, required: false}
          - {label: "Militancy", name: "militancy", widget: "number", valueType: "int", min: 1, max: 5, required: false}
          - {label: "Cynicism", name: "cynicism", widget: "number", valueType: "int", min: 1, max: 5, required: false}
          - {label: "Bullshit factor", name: "bullshit_factor", widget: "number", valueType: "int", min: 1, max: 5, required: false}

  
      - {label: "Photo", name: "photo", widget: "file", default: "/DiC-Logo-B.svg", media_library: {config: {multiple: false}}}
      - {label: "Bio", name: "bio", widget: "markdown", minimal: true, required: false}
      - {label: "Description", name: "body", widget: "markdown"}
  - name: "wtf" # Used in routes, e.g., /admin/collections/blog
    label: "WTF" # Used in the UI
    folder: "static/_wtf" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Content", name: "body", widget: "markdown"}
  - name: "psyche" # Used in routes, e.g., /admin/collections/blog
    label: "Psyche" # Used in the UI
    folder: "static/_psyche" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Content", name: "body", widget: "markdown"}
  - name: "living_dics" # Used in routes, e.g., /admin/collections/blog
    label: "Living Dictators" # Used in the UI
    folder: "static/_dics" # The path to the folder where the documents are stored
    filter:
      field: deathdate
      value: false
    fields:
      - {label: "Lost/hiding", name: "lost", widget: "boolean", default: false}
  - name: "dead_dics" # Used in routes, e.g., /admin/collections/blog
    label: "Mausoleum" # Used in the UI
    folder: "static/_dics" # The path to the folder where the documents are stored
    filter:
      field: deathdate
      value: true
    fields:
      - {label: "Cause of death", name: "cause", widget: "markdown", minimal: true, required: false}
